/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    themes: Theme;
    tags: Tag;
    bibliography: Bibliography;
    pages: Page;
    users: User;
    media: Media;
    subscribers: Subscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    bibliography: BibliographySelect<false> | BibliographySelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    navigation: Navigation;
    'index-pages': IndexPage;
    identity: Identity;
    subscriptions: Subscription;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'index-pages': IndexPagesSelect<false> | IndexPagesSelect<true>;
    identity: IdentitySelect<false> | IdentitySelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Numéro de série du carnet — affiché « n° 042 » côté lecteur. Manuel et stable.
   */
  numero: number;
  title: string;
  /**
   * URL-safe, ex : 'homonationalisme-diplomatie'. Sert à la route /billets/<slug>/.
   */
  slug: string;
  type: 'analyse' | 'note' | 'fiche';
  /**
   * Taxonomie multivaluée — un billet peut appartenir à plusieurs thèmes.
   */
  themes?: (number | Theme)[] | null;
  /**
   * Mots-clés libres, ajoutés à la volée depuis l’édition du billet. Différents des thèmes (qui sont structurants).
   */
  tags?: (number | Tag)[] | null;
  /**
   * Au moins un·e. La première entrée est auto-remplie au create avec l’utilisateur·rice connecté·e. Pour les externes (collègues hors Carnet), choisir « Externe » et saisir le nom + rattachement.
   */
  authors?:
    | {
        kind: 'user' | 'external';
        user?: (number | null) | User;
        /**
         * Ex. « Aïcha Touré »
         */
        name?: string | null;
        /**
         * Optionnel, ex. « LATTS ».
         */
        affiliation?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  /**
   * ~2-3 phrases — affichées en deck sous le titre.
   */
  lede: string;
  /**
   * Lexical — slash menu pour insérer des notes, citations longues, références biblio, figures.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Références listées en pied du billet, dans l’ordre choisi ici. Cliquables depuis les biblio_inline du corps.
   */
  bibliography?: (number | Bibliography)[] | null;
  /**
   * Calculé automatiquement depuis le corps au save.
   */
  readingTime?: number | null;
  /**
   * Identifiant stable, dérivé de l’année et du numéro (ex : carnet:2026-042).
   */
  idCarnet?: string | null;
  draft?: boolean | null;
  /**
   * Date à laquelle les abonné·es aux alertes mail ont été notifié·es de ce billet. Set automatiquement à la première publication, jamais re-déclenché.
   */
  notificationsSentAt?: string | null;
  /**
   * Calculé automatiquement — vrai si le corps contient au moins une zone marquée brouillon. Filtrable depuis la liste des billets.
   */
  hasDraftZones?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  /**
   * Ex : « Genre & géopolitique », « Queer theory », « Migrations & exil ».
   */
  name: string;
  /**
   * Identifiant URL, ex : 'genre-geopolitique'. Sert aussi de hash de tag inline (#queer-theory).
   */
  slug: string;
  /**
   * 1 à 2 phrases — apparaît en hero de la page /theme/<slug>/.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Mot-clé libre, ex : « Russie », « pinkwashing », « Conseil des droits de l’homme ».
   */
  name: string;
  /**
   * Auto-dérivé du nom (slugify). Sert d’ancre URL `/tag/<slug>/`.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  /**
   * Format Chicago author-date « Nom, P. » utilisé pour vous dans le bloc « Pour citer » des billets que vous co-signez. Si vide, la signature est dérivée automatiquement du nom affiché.
   */
  citationFormat?: string | null;
  /**
   * Root = compte propriétaire (1 seul, non supprimable). Admin = peut gérer les comptes. Éditeur·ice = édite le contenu.
   */
  role: 'root' | 'admin' | 'editor';
  /**
   * Géré automatiquement par le système d'invitation.
   */
  status?: ('pending' | 'active' | 'disabled') | null;
  invitation?: {
    tokenHash?: string | null;
    expiresAt?: string | null;
    invitedBy?: (number | null) | User;
    invitedAt?: string | null;
  };
  twoFactor?: {
    emailCodeHash?: string | null;
    emailCodeExpiresAt?: string | null;
    emailCodeAttempts?: number | null;
  };
  lastActivityAt?: string | null;
  lastLoginAt?: string | null;
  zotero?: {
    apiKey?: string | null;
    /**
     * Identifiant numérique — visible dans l’URL https://www.zotero.org/<userId>/library.
     */
    libraryId?: string | null;
    libraryType?: ('user' | 'group') | null;
    /**
     * Mis à jour automatiquement à chaque synchronisation.
     */
    lastSyncAt?: string | null;
    /**
     * Sert au diff incrémental côté Zotero (param `since`).
     */
    lastSyncVersion?: number | null;
    lastSyncAdded?: number | null;
    lastSyncUpdated?: number | null;
    lastSyncError?: string | null;
  };
  trustedDevices?:
    | {
        deviceId: string;
        fingerprintHash: string;
        label?: string | null;
        userAgent?: string | null;
        ip?: string | null;
        createdAt: string;
        expiresAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bibliography".
 */
export interface Bibliography {
  id: number;
  /**
   * Clé courte, ex : 'farris-2017'. Sert d'ancre `#bib-...` côté article.
   */
  slug: string;
  type: 'book' | 'chapter' | 'article' | 'paper' | 'web' | 'other';
  year: number;
  /**
   * Une ligne par personne (1er = auteur·ice principal·e, utilisé pour le tri et la citation courte). `firstName` peut rester vide pour les auteurs corporatifs (UNESCO, Conseil de l’Europe…).
   */
  authors: {
    lastName: string;
    firstName?: string | null;
    role: 'author' | 'editor' | 'translator';
    id?: string | null;
  }[];
  title: string;
  /**
   * Pour les livres : éditeur. Pour les articles : revue.
   */
  publisher?: string | null;
  place?: string | null;
  volume?: string | null;
  /**
   * Optionnel — collection éditoriale, série, etc.
   */
  journal?: string | null;
  /**
   * Ex : « 43-82 », « chap. 3 ».
   */
  pages?: string | null;
  url?: string | null;
  doi?: string | null;
  /**
   * Optionnel — note de lecture, raison de l'inclusion, mémo de contexte. Non publié.
   */
  annotation?: string | null;
  /**
   * Posée à la création — détermine si la ref est éditable au Carnet ou pilotée par Zotero.
   */
  source: 'manual' | 'zotero';
  /**
   * Identifiant interne Zotero — sert de pivot pour le sync.
   */
  zoteroKey?: string | null;
  /**
   * Numéro de version Zotero — sert au diff incrémental.
   */
  zoteroVersion?: number | null;
  /**
   * Renseigné pour les refs synchronisées — l'auteur du sync. Sert à scoper le picker biblio par user (cf v2).
   */
  owner?: (number | null) | User;
  authorLabel?: string | null;
  displayLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-safe, ex : 'about', 'colophon', 'mentions-legales'. Sert de match de route Astro.
   */
  slug: string;
  /**
   * ~150 caractères, affichée dans Google.
   */
  description?: string | null;
  /**
   * Si coché, demande aux moteurs de ne pas indexer.
   */
  noindex?: boolean | null;
  /**
   * Ex : « À propos », « Colophon ». Apparaît au-dessus du titre, en accent.
   */
  eyebrow?: string | null;
  /**
   * 1 phrase, affichée en gros sous le titre.
   */
  lede?: string | null;
  /**
   * Compose la page en empilant des sections (Prose, Figure, Citation).
   */
  sections?:
    | (
        | {
            /**
             * Apparaît en h2 si présent. Laisser vide pour pas de titre.
             */
            titre?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'prose';
          }
        | {
            image?: (number | null) | Media;
            legende?: string | null;
            /**
             * Ex : « Photo : Michel Rose, Paris, 2017 » ou « © UN Photo / Eskinder Debebe ».
             */
            credit?: string | null;
            align?: ('left' | 'center' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'figure';
          }
        | {
            text: string;
            /**
             * Ex : « Puar (2007), p. 23 ». Affichée en petits caractères mutés.
             */
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'citation_bloc';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Affiché en légende ou en infobulle selon le contexte.
   */
  title: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * « En attente » : lien de confirmation pas encore cliqué. « Actif·ve » : reçoit les mails de nouveaux billets. « Désabonné·e » : a cliqué sur le lien de désabo dans un mail, ne reçoit plus rien.
   */
  status: 'pending' | 'active' | 'unsubscribed';
  /**
   * SHA-256 du token envoyé dans le mail de confirmation. Stocké en base, jamais affiché en clair. Effacé après confirmation.
   */
  confirmTokenHash?: string | null;
  confirmTokenExpiresAt?: string | null;
  subscribedAt?: string | null;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'bibliography';
        value: number | Bibliography;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  numero?: T;
  title?: T;
  slug?: T;
  type?: T;
  themes?: T;
  tags?: T;
  authors?:
    | T
    | {
        kind?: T;
        user?: T;
        name?: T;
        affiliation?: T;
        id?: T;
      };
  publishedAt?: T;
  lede?: T;
  body?: T;
  bibliography?: T;
  readingTime?: T;
  idCarnet?: T;
  draft?: T;
  notificationsSentAt?: T;
  hasDraftZones?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bibliography_select".
 */
export interface BibliographySelect<T extends boolean = true> {
  slug?: T;
  type?: T;
  year?: T;
  authors?:
    | T
    | {
        lastName?: T;
        firstName?: T;
        role?: T;
        id?: T;
      };
  title?: T;
  publisher?: T;
  place?: T;
  volume?: T;
  journal?: T;
  pages?: T;
  url?: T;
  doi?: T;
  annotation?: T;
  source?: T;
  zoteroKey?: T;
  zoteroVersion?: T;
  owner?: T;
  authorLabel?: T;
  displayLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  noindex?: T;
  eyebrow?: T;
  lede?: T;
  sections?:
    | T
    | {
        prose?:
          | T
          | {
              titre?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        figure?:
          | T
          | {
              image?: T;
              legende?: T;
              credit?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        citation_bloc?:
          | T
          | {
              text?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  citationFormat?: T;
  role?: T;
  status?: T;
  invitation?:
    | T
    | {
        tokenHash?: T;
        expiresAt?: T;
        invitedBy?: T;
        invitedAt?: T;
      };
  twoFactor?:
    | T
    | {
        emailCodeHash?: T;
        emailCodeExpiresAt?: T;
        emailCodeAttempts?: T;
      };
  lastActivityAt?: T;
  lastLoginAt?: T;
  zotero?:
    | T
    | {
        apiKey?: T;
        libraryId?: T;
        libraryType?: T;
        lastSyncAt?: T;
        lastSyncVersion?: T;
        lastSyncAdded?: T;
        lastSyncUpdated?: T;
        lastSyncError?: T;
      };
  trustedDevices?:
    | T
    | {
        deviceId?: T;
        fingerprintHash?: T;
        label?: T;
        userAgent?: T;
        ip?: T;
        createdAt?: T;
        expiresAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  confirmTokenHash?: T;
  confirmTokenExpiresAt?: T;
  subscribedAt?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  branding?: {
    /**
     * Teinte d'accent appliquée à tout le site (point de la marque, item nav actif, kickers, liens dans les billets, boutons actifs, etc.).
     */
    accentColor?: ('#5a3a7a' | '#8a3a3a' | '#1f3a5a' | '#3a3a3a' | '#2d5a3d') | null;
    /**
     * Teinte de fond du Carnet — appliquée au body et aux zones neutres (header, footer, fond des billets, fond admin).
     */
    backgroundColor?: ('#f6f5f1' | '#fdfcf8' | '#ffffff' | '#f1efe8' | '#eee9dd' | '#e9eaec') | null;
  };
  reading?: {
    /**
     * Le mode classique empile les notes en bas du billet (style académique). Le mode en marge les place dans une colonne à droite, alignée sur le paragraphe qui les appelle (style « Tufte »). S'applique uniformément à tous les billets du Carnet. Cf issue #6.
     */
    notesMode?: ('classic' | 'sidenotes') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Onglets affichés dans le header du site, dans l'ordre. Le lien « Billets » (page d'accueil) reste toujours en première position et n'est pas listé ici. Pour cacher un onglet : on le supprime de la liste.
   */
  navHeader?:
    | {
        kind: 'index' | 'editorial';
        indexTarget?: ('archives' | 'themes' | 'subscribe') | null;
        page?: (number | null) | Page;
        /**
         * Override du libellé affiché. Sinon : le libellé natif de la page (eyebrow ou title pour les pages éditoriales, libellé par défaut pour les pages d'index).
         */
        label?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'navItem';
      }[]
    | null;
  navFooter?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index-pages".
 */
export interface IndexPage {
  id: number;
  home?: {
    /**
     * H1 de la page d'accueil. Entourer une portion de "*" pour la mettre en italique.
     */
    heroTitle?: string | null;
    /**
     * Paragraphe sous le titre de la page d'accueil.
     */
    heroLede?: string | null;
  };
  archives?: {
    /**
     * Si décochée, /archives/ renvoie 404.
     */
    enabled?: boolean | null;
    /**
     * H1 de la page /archives/. Entourer une portion de "*" pour la mettre en italique.
     */
    heroTitle?: string | null;
    /**
     * Paragraphe sous le titre de /archives/.
     */
    heroLede?: string | null;
  };
  themes?: {
    /**
     * Si décochée, /themes/ et /theme/<slug>/ renvoient 404.
     */
    enabled?: boolean | null;
    /**
     * H1 de la page /themes/. Entourer une portion de "*" pour la mettre en italique (ex. *thèmes*).
     */
    heroTitle?: string | null;
    /**
     * Paragraphe sous le titre de /themes/.
     */
    heroLede?: string | null;
  };
  subscribe?: {
    /**
     * Si décochée, /abonnement/ renvoie 404.
     */
    enabled?: boolean | null;
    /**
     * H1 de la page /abonnement/. Entourer une portion de "*" pour la mettre en italique.
     */
    heroTitle?: string | null;
    /**
     * Paragraphe sous le titre de /abonnement/.
     */
    heroLede?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity".
 */
export interface Identity {
  id: number;
  /**
   * Nom court qui apparaît dans le header (logo), le footer, le suffixe des onglets navigateur (« … — Nom »), les mails d'invitation et le flux RSS. Court de préférence (1 à 2 mots).
   */
  siteName?: string | null;
  /**
   * Nom du laboratoire de recherche, de la personne, du collectif… selon l'utilisation du carnet. Affiché en signature dans la baseline du footer et la description meta.
   */
  authorName?: string | null;
  /**
   * Affichée dans le footer (col 1).
   */
  baseline?: string | null;
  /**
   * Footer (col 1, sous la baseline, en mono).
   */
  copyrightLine?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  /**
   * Si décoché : /rss.xml renvoie 404, le lien « Flux RSS » du footer disparaît, et la section RSS de la page /abonnement/ disparaît.
   */
  rssEnabled?: boolean | null;
  /**
   * Si décoché : le formulaire d'inscription disparaît de /abonnement/ et aucun mail n'est envoyé à la publication des nouveaux billets — même pour les abonné·es déjà actif·ves (qui ne sont pas supprimé·es pour autant : on peut réactiver plus tard).
   */
  emailEnabled?: boolean | null;
  /**
   * URL complète du profil Mastodon.
   */
  mastodon?: string | null;
  /**
   * URL complète du profil Bluesky.
   */
  bluesky?: string | null;
  /**
   * URL complète du profil ORCID.
   */
  orcid?: string | null;
  /**
   * URL complète de la page HAL.
   */
  hal?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        accentColor?: T;
        backgroundColor?: T;
      };
  reading?:
    | T
    | {
        notesMode?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  navHeader?:
    | T
    | {
        navItem?:
          | T
          | {
              kind?: T;
              indexTarget?: T;
              page?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  navFooter?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index-pages_select".
 */
export interface IndexPagesSelect<T extends boolean = true> {
  home?:
    | T
    | {
        heroTitle?: T;
        heroLede?: T;
      };
  archives?:
    | T
    | {
        enabled?: T;
        heroTitle?: T;
        heroLede?: T;
      };
  themes?:
    | T
    | {
        enabled?: T;
        heroTitle?: T;
        heroLede?: T;
      };
  subscribe?:
    | T
    | {
        enabled?: T;
        heroTitle?: T;
        heroLede?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity_select".
 */
export interface IdentitySelect<T extends boolean = true> {
  siteName?: T;
  authorName?: T;
  baseline?: T;
  copyrightLine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  rssEnabled?: T;
  emailEnabled?: T;
  mastodon?: T;
  bluesky?: T;
  orcid?: T;
  hal?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}